# Generated by Django 4.1.13 on 2025-08-26 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 26, 11, 17, 44, 46635)),
        ),
    ]
