# Generated by Django 4.1.13 on 2024-09-26 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 26, 16, 4, 26, 345013)),
        ),
    ]
