# Generated by Django 4.2.23 on 2025-09-09 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_document_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 9, 8, 17, 25, 691900, tzinfo=datetime.timezone.utc)),
        ),
    ]
